# Generated by Django 4.1.13 on 2024-05-09 15:05

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStreamResult',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('threshold', models.IntegerField()),
                ('similarity', models.TextField(blank=True)),
                ('path_frame', models.TextField(blank=True)),
                ('detected_time', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Camera Stream Result',
                'verbose_name_plural': 'Camera Stream Result',
            },
        ),
        migrations.CreateModel(
            name='RecordedVideo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.TextField()),
                ('video_path', models.TextField()),
            ],
            options={
                'verbose_name': 'Recorded Video',
                'verbose_name_plural': 'Recorded Videos',
            },
        ),
        migrations.CreateModel(
            name='RecordedVideoResult',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('similarity', models.TextField(blank=True)),
                ('path_video', models.TextField(blank=True)),
                ('detected_time', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('recorded_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_search.recordedvideo')),
            ],
            options={
                'verbose_name': 'Recorded Video Result',
                'verbose_name_plural': 'Recorded Video Results',
            },
        ),
    ]
