# Generated by Django 4.1.13 on 2024-05-21 12:25

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('individual_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualSearchFromRecordedVideo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('similarity', djongo.models.fields.JSONField(default=list)),
                ('path_video', models.TextField(blank=True)),
                ('recognition_path', models.TextField(blank=True)),
                ('detected_time', djongo.models.fields.JSONField(default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('recorded_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual_search.recordedvideo')),
            ],
            options={
                'verbose_name': 'Recorded Video Result',
                'verbose_name_plural': 'Recorded Video Results',
            },
        ),
        migrations.DeleteModel(
            name='RecordedVideoResult',
        ),
    ]
